import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Nastaliq_Urdu } from "next/font/google";
import "./globals.css";
import { NavigationHeader } from "./components/NavigationHeader";
import Footer from "./components/Footer";
import { getFooter } from "./lib/footer";
import { LanguageProvider } from "./context/LanguageContext"; // Import Provider
import { getServerLocale } from "./lib/get-locale"; // Import Helper
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notoNastaliq = Noto_Nastaliq_Urdu({
  variable: "--font-nastaliq-urdu",
  subsets: ["arabic", "latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const locale = await getServerLocale();
    const footerData = await getFooter(locale);

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${notoNastaliq.variable} antialiased`}
      >
        <LanguageProvider initialLocale={locale}>
          <NavigationHeader />
          {children}
          <Footer data={footerData} locale={locale} />
        </LanguageProvider>
      </body>
    </html>
  );
}
